<link rel="stylesheet" href="{{asset('backend/admin/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/font-awesome.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/ionicons.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/datepicker3.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/all.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/dataTables.bootstrap.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/jquery.fancybox.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/AdminLTE.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/_all-skins.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/css/on-off-switch.css')}}"/>
<link rel="stylesheet" href="{{asset('backend/admin/css/summernote.css')}}">
<link rel="stylesheet" href="{{asset('backend/admin/style.css')}}">